
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: database_name
  username: test2
  password: test2
  host: localhost
  port: 5432

test:
  <<: *default
  database: database_name

production:
  <<: *default
  url: <%= ENV['DBURI'] %>